#!/bin/sh
COMMIT_MSG_FILE=$1
COMMIT_SOURCE=$2
SHA1=$3

# do not process if ammend commit
if [ -n "$(head -n1 $COMMIT_MSG_FILE)" ]; then
    exit 0
fi

# get issue number
BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)
ISSUE_NUM=$(echo $BRANCH_NAME | sed -e 's_feature/#\([0-9][0-9]*\)[^0-9]*_\1_g')

# do not process if issue number is not available
if [ -z "$ISSUE_NUM" ]; then
    exit 0
fi

sed -i.bak "1s/^/refs #$ISSUE_NUM /g" "$COMMIT_MSG_FILE"
exit 0
